#!/bin/bash

#############################################################################
#                                                                           #
# Download Videos which are in the ARD Mediathek                            #
#                                                                           #
# Author: nv1t <nuit@hoeja.de>                                              #
#                                                                           #
#############################################################################

DOWN=2
COUNT=1


if [ -z "$1" ]
then
    echo ""
    echo "    Usage: $0 <videolink>"
    echo ""
    echo ""

    exit 255
fi


for i in `curl -s $1 | grep "rtmp" | sed 's/.*"\(mp4:[^\?]*\)?.*/\1/g'`;
do
	if [[ $COUNT -eq $DOWN ]]; then
		echo "Download"
		rtmpdump -e --host vod.daserste.de --app ardfs/ --playpath "${i}" -o $2;
	fi
	COUNT=$(($COUNT+1))
done;
