#!/bin/bash
# generates a valid cookie in $cookiefile and uses that cookie
# to read the frontpage of a account

email=""
pass=""
cookiefile="fb_cookies.txt"

curl -s --cookie $cookiefile --cookie-jar $cookiefile -d "charset_test=%E2%82%AC%2C%C2%B4%2C%E2%82%AC%2C%C2%B4%2C%E6%B0%B4%2C%D0%94%2C%D0%84&locale=en_US&email=${email}&pass=${pass}&pass_placeholder=&charset_test=%E2%82%AC%2C%C2%B4%2C%E2%82%AC%2C%C2%B4%2C%E6%B0%B4%2C%D0%94%2C%D0%84" --user-agent "Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.0.6) Gecko/2009011913 Firefox/3.0.6 (.NET CLR 3.5.30729)" "https://login.facebook.com/login.php?login_attempt=1"

curl -v --location --cookie $cookiefile --cookie-jar $cookiefile  --user-agent "Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.0.6) Gecko/2009011913 Firefox/3.0.6 (.NET CLR 3.5.30729)" "http://facebook.com/"

